### ISSUE TITLE
Pip package

### ISSUE THREAD

**Issue by eleijonmarck** [holoviz/holoviz#100]
Hello,

We would want to see the use case for intergrating pyviz into some of our tools. However we right all python.

Is there a way of installing everything without using `conda`

Preferably:
`pip install pyviz`

Or providing a makefile
`make install`

**Comment by jbednar** [comment]
That's tricky -- even if you write pure Python, if you depend on anything that itself depends on things that are not Python, then you need to track binary dependencies, which Pip does not do very well.  That said, pyviz used to require conda specifically because Datashader required it, which in turn was because Numba required it, but now that numba ships via pip, Datashader also ships via pip, and it *may* be possible for pyviz to ship via pip.

@philippjfr, GeoViews would then be the key requirement.  I assume it would be difficult to get all the binary dependencies of GeoViews via pip?  Would it make sense for pyviz to be pip-installable *except* for GeoViews and its dependencies?

**Comment by eleijonmarck** [comment]
@jbednar thank you for the consideration. We build a exploratory platform, however we have tried to combine `conda` with `pip` but were unsuccessful. Too many (weird) interactions too be able to maintain in production as well as setting it up for devs.

Perhaps a docker image would be better?

**Comment by jbednar** [comment]
The conda team has been prioritizing improving interactions with pip, and there may already have been improvements there, if you use the latest conda releases.  The goal is to minimize those weird interactions, but I don't know if the specific ones you encountered were the ones that have been addressed so far.

You are certainly welcome to make a docker image and distribute it.  You should be able to set that up already now just by pip-installing the list of packages that pyviz includes, omitting any that don't have pip equivalents (which I think is just geoviews?).

**Comment by ceball** [comment]
Some quick notes:
  * geoviews already has a package on pypi for pip, but it depends on cartopy, and whether you can pip install cartopy or not depends on how your system is set up (https://scitools.org.uk/cartopy/docs/v0.15/installing.html)
  * the geo stack is often problematic even if you use conda
  * a pip installable pyviz package will soon appear on pypi (as part of ongoing work), and I guess it will have optional extras (the core package will be fine to pip install)
  * if you're integrating pyviz into something else, do you need (or even want?) all of pyviz? Could you pip install only the underlying packages you need?
  * I imagine the kinds of conda/pip interactions being referred to are not improved in any released conda, *but* I think a preview of better conda/pip interaction might be an opt-in setting for one of the next conda releases

**Comment by eleijonmarck** [comment]
> if you're integrating pyviz into something else, do you need (or even want?) all of pyviz? Could you pip install only the underlying packages you need?

* Would certainly be effective just to have them as pip packages to install the underlying components.

> I imagine the kinds of conda/pip interactions being referred to are not improved in any released conda, but I think a preview of better conda/pip interaction might be an opt-in setting for one of the next conda releases

* We have a contributor to the pyarrow , parquet team and pypy as well. He did not manage to setup it properly so we have had the competence to be able to do that.

**Comment by jbednar** [comment]
I'm not sure what the remaining issue is?  It sounds like datashader was the last remaining conda-only package, so you should be all set?

**Comment by eleijonmarck** [comment]
I guess we are waiting for :
> a pip installable pyviz package will soon appear on pypi (as part of ongoing work), and I guess it will have optional extras (the core package will be fine to pip install)

Then it can be closed?

**Comment by ceball** [comment]
Having now tried this myself, I've found the first stumbling block is that there are currently only outdated packages (with respect to pyviz.org material) on pypi for: panel, bokeh, geoviews, holoviews, param.

Basically, they all need to have releases before we can offer a pip package that's up to date with the tutorial content at pyviz.org. (Or, those projects could upload dev releases to pypi, for people to install via `pip --pre`.)

We could put up a pypi package for 0.9.11 (rather than current 0.9.12), since its dependencies appear to be on pypi, but that wouldn't match the tutorial content at pyviz.org.

**Comment by jbednar** [comment]
Please do release a pip package for 0.9.11, and then once the underlying projects are released we can release 0.9.13 (skipping over the too-rushed 0.9.12).

**Comment by ceball** [comment]
I realize now that a pip package for 0.9.11 would unfortunately have a broken `pyviz --install-examples` command (see https://github.com/pyviz/pyviz/issues/113#issuecomment-426364505). Along with such a package not matching the tutorial at pyviz.org, I think that tips me towards accepting that it's probably better just to wait. Or, persuade bokeh to put pre-releases on pypi (for installation via `pip --pre` (and do the same ourselves).

**Comment by jsignell** [comment]
I think this can be safely closed. We are building a pip package, and all the underlying pyviz libraries also have pip packages.
