### ISSUE TITLE
nyc_taxi_50k.parq isn't complete "small dataset" replacement for nyc_taxi_wide.parq?

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#108]
When https://github.com/pyviz/pyviz/blob/master/exercises/Exercise-4-dynamic-interactions.ipynb is run with nyc_taxi_50k.parq (on travis), this error seems to occur:

![x1](https://user-images.githubusercontent.com/1929/46200239-06bd6e80-c309-11e8-943d-069dc8109f6b.png)

**Comment by marcbernot** [comment]
This is because trips = taxi_trips_stream() generates the dataframe of all the trips during one particular hour, and this for successive hours.
For the nyc_taxi_wide.parq file, these dataframes are never empty, but for the nyc_taxi_50k.parq there are many instances of hours without a single trip.
Thus the dataframe given by next(trips) is sometimes empty hence the KeyError.

I guess this code should be made robust to the occurence of empty dataframes rather than changing nyc_taxi_50k.parq.

**Comment by jbednar** [comment]
That's an excellent suggestion, thanks!

**Comment by jsignell** [comment]
Removed from tutorial
