### ISSUE TITLE
Can't run taxi player app on windows

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#109]
I noticed during #81 so can't investigate right now.

There seem to be multiple problems, but the first is some kind of decoding error. It's hard to say more, since I get only a redacted "ERROR" message from somewhere in the pyviz stack (bokeh?). My *guess* (it's really a guess) is somewhere in the pyviz stack opens the app's main.py file as text, and assumes the default encoding of text files is utf-8 - which is not true (at least, as of python 3.6 on windows). (The main.py file is fine to run with python itself rather than bokeh, since in python 3.6 python source code files are assumed to be utf-8 by default.)

Need to investigate further (e.g. does it happen with latest bokeh? does the app work on other platforms?).

**Comment by marcbernot** [comment]
I had no such problem on window10  (fresh install with the latest miniconda python 3.7 then following the installation instructions from pyviz.org). We are talking about server_app.py right?

I already had encoding problems with the nyc_taxi_wide.parq file though. This happens by using pyarrow rather than fastparquet. Notice that when both are installed, pandas.read_parquet uses pyarrow by default.
`pd.read_parquet('nyc_taxi_wide.parq',engine='pyarrow')`-> encoding error
`df = pd.read_parquet('nyc_taxi_wide.parq',engine='fastparquet')`-> no error 
Writing a new parquet file with `df.to_parquet('new_nyc_taxi_wide.parq',engine='fastparquet')` yields a parquet file that can be read by both pyarrow and fastparquet.
I think you should replace nyc_taxi_wide.parq to get rid of this encoding error even if you recommend to work in a separate environment. I guess that some people just take the tutorials and try them in their already existing environment (this is what I did first).

**Comment by ceball** [comment]
I was talking about the taxi player app. However, since I made this issue, that app has been changed to fix the first issue I encountered (although I think the fix is just hiding the underlying problem).

**Comment by ceball** [comment]
I haven't revisited the app myself yet, so thanks for the info about the pyarrow/fastparquet issue. 

Your posts and investigations on pyviz have been very helpful, thanks.

**Comment by jsignell** [comment]
That app no longer exists in the tutorial. So closing :)
