### ISSUE TITLE
Pyviz - Pycharm support

### ISSUE THREAD

**Issue by Sravz-Solv** [holoviz/holoviz#166]
When using Pycharm, none of the plots are displayed even as the code complies without any errors. This is both in the Juypter interface of Pycharm as well as the regular interface. Are HoloViz tools (holoviews really) supported on PyCharm IDE? 
![image](https://user-images.githubusercontent.com/44657023/55186608-32a09c00-5154-11e9-83df-7f61148784ae.png)

**Comment by jsignell** [comment]
Our tools don't support PyCharm yet, but we hope to build support for that in the near future.

**Comment by mmartini-usgs** [comment]
I'd like to put in another vote of support for pycharm support.

**Comment by philippjfr** [comment]
As of now there is basically no chance of supporting PyCharm. As far as we are aware PyCharm does not support any Javascript which makes it impossible to render bokeh or plotly output. Additionally even if Javascript is eventually supported it will still be missing the Jupyter comm channels which make it possible to support a wide range of interactivity.

**Comment by jbednar** [comment]
I.e., it's currently up to PyCharm to add the underlying technical capability that would allow it to support Bokeh, Plotly, HoloViews, GeoViews, and hvPlot visualizations; it's not something that can be done by the plotting libraries themselves.

**Comment by Sravz-Solv** [comment]
I use the work around of saving plot  I generate as a webpage and then just open that webpage. This works well for me. For example:

```
hv.save (plot_handle, plot_name)
webbrowser.open_new_tab (plot_name)
```

I am wondering if something similar can be done for everyone. So far, I have not felt like I am missing any additional functionality but might be just be blissfully unaware of what I am missing.

**Comment by Sravz-Solv** [comment]
Thanks for response. I will open a ticket with pycharm if this is something they would ever consider.

**Comment by philippjfr** [comment]
>I am wondering if something similar can be done for everyone. So far, I have not felt like I am missing any additional functionality but might be just be blissfully unaware of what I am missing.

You are definitely missing out on a bunch of features by doing that. That said, there is a workaround now that will support all features, which is to use [panel](http://panel.pyviz.org/) to display the output in a new browser tab using:

```python
import panel as pn
pn.panel(hv_obj).show()
```

**Comment by zbarry** [comment]
@Sravz-Solv - didn't see a ticket open, so went ahead and created one:

https://youtrack.jetbrains.com/issue/PY-37071

I think anyone can vote on issues they particularly care about, which probably informs PyCharm devs about relative priorities for features that they might consider working on.

**Comment by DuaneNielsen** [comment]
After messing around for a bit, I managed to get this working example in pycharms Sciview mode.

Not sure how useful it is yet, but it's better than nothing.

```
import holoviews as hv
import holoviews.plotting.mpl

hv.output(fig='svg')
renderer = hv.plotting.mpl.MPLRenderer.instance(dpi=120)
curve = hv.Curve(range(10))
renderer.show(curve)
```
![image](https://user-images.githubusercontent.com/11070508/71562832-d4824b80-2a3a-11ea-9bc1-afe51f254e63.png)

**Comment by DuaneNielsen** [comment]
and here's something a bit fancier.  However I found quite a few things don't work with matplotib renderer, so it seems a bit hit and miss.

```
import holoviews as hv
import holoviews.plotting.mpl
import numpy as np

hv.extension('bokeh')
hv.output(fig='png')
renderer = hv.plotting.mpl.MPLRenderer.instance(dpi=120)

points = hv.Points(np.random.randn(100, 2))
points = points.hist(dimension=['x', 'y'])

renderer.show(points)
```
![image](https://user-images.githubusercontent.com/11070508/71563094-f1208280-2a3e-11ea-8c7e-e3f251971f78.png)

**Comment by DuaneNielsen** [comment]
After looking into it a bit further.  I don't think matplotlib renderer is the answer.

Basically, as soon as you try to plot a bokeh visualization with a matplotib renderer, it's game over.

The problem is, so many of the visualizations in Holoviews assume you are working in something like Ipython notebook, or in in some kind of HTML5 capable editor.

Unfortunately, these types of editors don't scale well when your project has a few thousand lines of pytorch or tensorflow code.

So I think this is a good library if you want to make fancy charts of raw data to impress your boss.  Or if you want to make a fancy online demo of a project you already completed.  But for debugging the insides of a system of neural networks... I don't think it's so good.

Ah well.. the quest for the perfect library for visualization of deep learning continues....

**Comment by jbednar** [comment]
Normally the visualizations are *viewed* in a notebook, but any substantial code will be in a proper Python module or collection of modules so that it can be organized properly and maintained. Such code can return HoloViews objects that can then be viewed when needed in notebooks. That's certainly the original design and intention for HoloViews.

**Comment by DuaneNielsen** [comment]
Yeah, I think that's a fine way to use this library.  My use case is a bit different, it's to create live visualizations of activation maps during training of a neural network.  So I can see what's going wrong with my math during training.  I suspect that's not what this library is really aimed at.

What I'm looking for is a lightweight way I can drop just a few lines of code in my project to create a visualization of a function, or analysis snapshots of tensor data for tensorboard.

The problem with the renderers in Holoviews, is by requiring phantomJS in bokeh to generate images to be saved into tensorboard, it makes everything really slow, and introduces nodejs dependencies into a pure python project.

HV would be great if it was had a single pure python/c++ plotting engine and just drew cool graphs like it says on the tin.  However it seems that it's rather well designed wrapper around a Frankenstein of 3 opensource projects!  And it's not easy to just un-stitch the matplotlib part of the Frankenstein.  The moment you try to do that, like I said.. game over.

It looks good for the ipython notebook crowd.  That's a big crowd, so I'm sure it's in good company.

**Comment by jbednar** [comment]
> Basically, as soon as you try to plot a bokeh visualization with a matplotib renderer, it's game over.

That's putting it a bit strongly, but yes, it does take work to use Matplotlib to view a HoloViews object customized for Bokeh; various options a user added for Bokeh will need translating. But you don't have to do that in practice if you stick with a Matplotlib backend; there's no translation cost then.  So I'm not sure what the issue is here.

> The problem is, so many of the visualizations in Holoviews assume you are working in something like Ipython notebook, or in in some kind of HTML5 capable editor.

For interactivity, yes. But interactive plots weren't even supported in HoloViews for the first several years of its existence; until 2016 it only supported Matplotlib rendering to PNG or SVG.  It should be perfectly reasonable to use HoloViews with static Matplotlib plots.

> Unfortunately, these types of editors don't scale well when your project has a few thousand lines of pytorch or tensorflow code.

We would never recommend that people use a Jupyter notebook to maintain thousands of lines of code, and we certainly do not do that ourselves. Personally, I use Emacs for all my Python modules, and use notebooks only for exploring things, not for maintaining the codebase itself. And my colleague @jlstevens uses Emacs for both purposes, by editing notebooks directly from Emacs using https://github.com/pyviz-dev/nei (still quite alpha!). Personally, I think the larger the scale of the project, the more sense it makes to use something like HoloViews where you can build visualization capability in from the start, instead of painfully having to build a plot every time you want to see what's going on.


> to create live visualizations of activation maps during training of a neural network. So I can see what's going wrong with my math during training. I suspect that's not what this library is really aimed at.

On the contrary; that's precisely what this library was created for!  As you can see from the now-stale site topographica.org, HoloViews was first developed as a way to flexibly visualize the training of our neural networks so that we could understand how they were working, detect issues with the math and our code, and adjust parameters. In our case at the time the neural networks were simulating the brain rather than trying to solve practical problems, but the workflow shares a lot with ML model training. We wanted to make it simple and costless to reveal what was going on at every stage of the networks and how the various behaviors of the networks varied over time, so we focused on making every single data structure (inputs, outputs, activations, weights, etc.) able to visualize itself. That way we could freely explore (either in a notebook or in a GUI) anything we wanted with essentially zero code at the point of exploration and very little code at the point the data was generated.

>What I'm looking for is a lightweight way I can drop just a few lines of code in my project to create a visualization of a function, or analysis snapshots of tensor data for tensorboard.

Sounds like HoloViews to me!

> The problem with the renderers in Holoviews, is by requiring phantomJS in bokeh to generate images to be saved into tensorboard, it makes everything really slow, and introduces nodejs dependencies into a pure python project.

It sounds like you would want to use the Matplotlib backend. Nowadays, the main HoloViews developers primarily focus on adding features to the interactive Bokeh and Plotly backends, but we are still fully committed to the Matplotlib backend, which does not require PhantomJS and renders to PNG or SVG quite quickly.  

Note that even for Matplotlib rendering, HoloViews still needs JavaScript support for you to exploit one of its main features, i.e. easily exploring data too high-dimensional to fit on the screen.  E.g. our original neural networks had a two dimensional topology (as do many CNNs nowadays), meaning that visualizing the weights over time required three or more dimensions, which we approximated using JS widgets to select values for all dimensions not displayed. If you don't need that, you can get by with just the PNG or SVG rendering, but I would hate to give up that capability! If an editor provided some other way to have slider widgets that wasn't JS, it probably wouldn't be too difficult to support it...

> HV would be great if it was had a single pure python/c++ plotting engine and just drew cool graphs like it says on the tin. 

If you look at the first line on our website, it doesn't promise to draw cool graphs; quite the opposite -- "Stop plotting your data - annotate your data and let it visualize itself." HoloViews is about letting you focus on understanding your data (or networks, or whatever), without spending all your time writing plotting code.

> However it seems that it's rather well designed wrapper around a Frankenstein of 3 opensource projects! And it's not easy to just un-stitch the matplotlib part of the Frankenstein. The moment you try to do that, like I said.. game over.

Still not sure what you're getting at there, but the whole point of wrapping multiple plotting libraries is that each one offers unique functionality, which seems to be what you're requesting in this case (i.e. quick JS-free rendering to PNG, which is only currently available from the Matplotlib backend).  HoloViews is designed to let you have that capability if you need it, so if it's failing to do so in a particular case, please file a bug report!  And in the meantime, you are welcome to keep looking for other libraries, but you should do so under the knowledge that HoloViews was in fact very specifically designed and implemented for precisely the situation you are describing.

**Comment by DuaneNielsen** [comment]
Thanks for your detailed response.

Perhaps what I'm missing here is the "howto".  Do you have example projects where you have done debug visualizations of activations of a neural net using holoviews?  I would be very interested in taking a look to get ideas for my own projects.

Currently, I'm spitting out matplotlib plots to png and sending to tensorboard or displaying them with cv2.  If there is a better way I'm all ears...

Thanks again.

**Comment by jbednar** [comment]
Good question.  No, I don't think we have anything very relevant that we can make public.  The best I can think of are the [Image Classification example at EarthML](https://earthml.holoviz.org/topics/Image_Classification.html) and [Philipp's PhD thesis](http://thesis.philippjfr.com) from a few years ago. Looking over the thesis now, nearly all the figures in there focus on matching scientific experiment results, rather than analyzing the internal behavior of the networks, which is something we mainly did for debugging rather than publishing so it didn't end up in the final document. The Image Classification one also only focuses on results, alas.

As for how to handle viewing the rendered PNGs, I haven't tried TensorBoard, and cv2 seems as good a way as any to view them.  You could post a detailed description of your editing/viewing workflow at https://discourse.holoviz.org and see if anyone has any suggestions for how to improve it...

**Comment by gmoutso** [comment]
> You are definitely missing out on a bunch of features by doing that. That said, there is a workaround now that will support all features, which is to use [panel](http://panel.pyviz.org/) to display the output in a new browser tab using:
> 
> ```python
> import panel as pn
> pn.panel(hv_obj).show()
> ```
Can you elaborate on what panel offers beyond exporting to html using %%output or hv.save?

I want to migrate from jupyter notebooks to emacs (py or org) using [emacs-jupyter](https://github.com/dzop/emacs-jupyter). Any insight you have of integrating holoviews/hvplot using this method would be helpul! I connect to a remote jupyter server if that makes a difference.

**Comment by philippjfr** [comment]
>Can you elaborate on what panel offers beyond exporting to html using %%output or hv.save?

Sure, ``pn.panel(...).show()` will open a new browser window automatically and start a bokeh server instance which ensures all the interactive features that HoloViews provides actually work, a static export generated using save does not have access to a Python kernel to support those features. That said if you don't use those features there's not much difference.

**Comment by majidam20** [comment]
> ```python
> import panel as pn
> pn.panel(hv_obj).show()
> ```

this is also for me works well. thanks man!!!

**Comment by gmoutso** [comment]
There is also a recent commit to `.show(port=8888, threaded=True,verbose=True,show=False)` that looks superb when running Jupiter on a remote server. (edit: haven't managed to make it work yet)

**Comment by jbednar** [comment]
I don't think that there's any action the HoloViz developers can take to improve PyCharm support currently, so I'll close this, but it will remain in the archives to help anyone who wants to read about the issues!

**Comment by bourov** [comment]
Looks like PyCharm has supported bokeh since v2019.3, https://youtrack.jetbrains.com/issue/PY-36381

Does this change possibility of holoviews working in pycharm ?

**Comment by jbednar** [comment]
HoloViews and Panel can't be fully supported in PyCharm until Bokeh's interactive widgets are supported, which does not appear to be on their roadmap yet:  https://youtrack.jetbrains.com/issue/PY-37562
