### ISSUE TITLE
PyViz topics - where should they live

### ISSUE THREAD

**Issue by jsignell** [holoviz/holoviz#172]
I am opening this issue to capture various ideas of where and how to store in-depth examples that span pyviz projects and possibly involve larger datasets. We call these types of examples "topics". 

## Current state of pyviz-topics GH org
We have created a "pyviz-topics" GH org to handle these types of things. So far that org has 3 repos: 
 - [EarthML](https://github.com/pyviz-topics/earthml) and [EarthSim](https://github.com/pyviz-topics/earthsim) are essentially websites with specific environments, and tutorials and topics that relate roughly to machine learning and simulations in the Earth Science context
 - [contrib](https://github.com/pyviz-topics/contrib) is intended as a location where users can submit examples with a low barrier to entry. These examples are not necessarily expected to be polished or maintained.

## pyviz-demos
There is another GH org called [pyviz-demos](https://github.com/pyviz-demos) that takes a different, very binder-driven, approach. That organization contains a repo for each example (a repo can be as little as a notebook and config files).

# Proposals
I am going to write down every idea that I can think of for how to keep track of the examples.

## Each repo is an example (like pyviz-demos)
This is **my preferred approach**. I think it will serve us best in the long-run and make it easy to pull examples for use in tutorials and talks. This matches most closely the current pattern of just throwing independent notebooks up on anaconda.org. And it would hopefully help prevent duplication. I think for this to work we'd need a good template repo.

PROS:
 - Flat hierarchy might make examples more discoverable, especially when paired with a gallery page that shows thumbnails of them.
 - Works well with binder.
 - Ensures environment isolation.
 - If there are particular updates that an example needs, those issues can be made right on the repo for the example. 
 - If example is already a repo - this will be a very easy move. 
 - Good for talks that use one example. Just point to the one repo. User doesn't need to know about the others. 
 - Could use labels to filter which projects use panel, or something

CONS:
 - Flat hierarchy might make examples less discoverable since they aren't grouped by content.
 - Lots of overhead with config files.
 - Hard to do something with all the repos.
 - We already have 3 repos in there that don't match this pattern. Are they just exceptions?

## Subject area repos with examples sorted
As a start, we could capture all the topics at datashader topics by adding "politcs", "networks",  "geo" (might be able to use symbolic links to link census in both geo and politics). 

PROS:
 - Similar to what we already have going with EarthML and EarthSim.
 - Might improve discoverability if people come in knowing that they want astro examples or something. 
 - Will highlight what pyviz is proven to be good at (nd earth science data probably, also points on a map)
 - Could make some nice discipline-specific sites that might lure people in.

CONS:
 - Hard to sort examples into content areas (eg is census "politics" or "geo"?)
 - Will highlight gaps in the types of long-form examples that we've written for pyviz and possibly make it look like pyviz isn't good at these things even if it might be (BI probably)
 - There are multiple axes on which we might want to sort examples. I could imagine someone saying I just want to see an example that uses panel and hvplot (but maybe that isn't supposed to be a topic).
 - Can't be binderized as easily

## One new repo with all the examples in it

Within that repo there would be top level config files, and then directories where each directory corresponds to one example. Inside each of these there would be an environment.yml, possibly a catalog.yml if intake is being used, and at least one notebook.

PROS:
 - Less overhead with duplicated config files. 
 - Could make it into one website using gh-pages.

CONS:
 - Environment isolation isn't as strict.
 - Meaningless nesting.
 - Harder for new users to discover just the example that they are interested in. 
 - Can't be binderized as easily

## Related issues
 - The migration from datashader to pyviz (#84). 
 - Topics should indicate what they demonstrate (#85)
 - Users should be able to contribute (#147)

**Comment by jsignell** [comment]
Maybe we should have standalone examples in pyviz-demos and then have them sorted into topic areas in pyviz-topics.

**Comment by jbednar** [comment]
I'm still thinking about this, but a few observations:

## Topic areas

Our existing EarthML and EarthSIM repos make sense both because of a coherent topic area and because of a shared environment.  The topic area coherence makes it possible to make a public-facing website that makes sense and groups related tasks together for humans to process, and the shared environment makes it possible to maintain such examples as a group.  But note that the shared environment only works up to a point, e.g. the EarthSim notebooks include some that have different dependencies that are problematic and thus best avoided for the other notebooks, and the EarthML environment could eventually balloon to include all ML and pre-processing libraries in Python if we aren't careful.  So even in those two cases having a shared environment is only a sort-of solution; probably eventually in all of them we would want a shared base environment plus certain extra packages per example. The result is then that the shared topic area is what will make those sites be a coherent thing moving forward.

With that in mind, I don't think we can or should try to group the actual examples by topic area in their underlying storage.  E.g. even GrabCut is linked from EarthML to EarthSim already, and we can't in general assign any unambiguous topic area to each example.

In any case I don't think we have to worry too much about discoverability of the various topic examples; my hope is to have the examples organized somewhere in a way that we can maintain them effectively and can defend static URLs for them, and at that point we can have each of our various sites and topic areas point to the underlying projects wherever they may be.  Each project can have many links to it, but just one master source.

## Organizing each example

I *do* worry a lot about the discoverability of the source code inside each example.  E.g. in 
 https://github.com/pyviz-demos there is currently tons of boilerplate that makes each repo seem like a brick wall in terms of exploring. E.g. if I go to https://github.com/pyviz-demos/clifford-interact, I see 8 different files, most named quite obscurely, and I have no way to guess that only app.ipynb has anything interesting in it. In most cases, the source code is the point, but the current setup makes it entirely non-obvious that the underlying source code is clear, human readable, and ready to explore; instead the current setup only encourages playing with the deployed app without seeing the relation between the app and the underlying code. Our focus is all about easing the path to the finished product, using as little and as simple code as possible, and if we obscure that code in a pile of distracting items we're doing ourselves a disservice.

Maybe if these are handled with some technology other than binder there won't be the need for all this boilerplate (eliminating postBuild, panelserverextension.py and probably .gitignore (surely not really needed for this type of repo))?  That would leave app.ipynb (clearly a notebook), environment.yml (clearly the environment), assets (optional), and maybe README.md?  It's annoying to duplicate LICENSE across every single project, but that seems like an unavoidable consequence of choosing the per-repo approach. 

## One new repo with all the examples in it

Having one repo with all the examples in it would avoid duplicating the LICENSE and maybe some boilerplate.  I don't agree that the environment isolation would _necessarily_ be any less strict; can't we enforce strictly separated environments even then?  

What meaningless nesting would there be?  Seems like a repo consisting of a bunch of examples isn't meaningless nesting, it's just saying that we're going to maintain this group of items in a similar way.  Whether that is via a Github org grouping them in that way, or a github repo grouping them in that way, doesn't seem like a meaningful distinction in terms of nesting.

I don't think this approach makes it "Harder for new users to discover just the example that they are interested in."  Seems like they can discover projects just the same whether they are grouped by github org or by repo; in both cases they are likely to discover them through the pointers we make to them (from pyviz.org, etc.)  What it does do is make it harder for new users to *extract* a single example they are interested in.  But conversely, using one repo for the whole set of examples makes it more likely that people will explore *multiple* examples; with one repo per project people are very unlikely to explore very many repos before they get tired of cloning repos and running the setup.  And ideally we'd want users to be able to explore a single repo but also easily explore a whole group of them (e.g. to see what Panel can do, or HoloViews).  And I don't see how we can maintain dozens of dozens of separate repos, without writing a whole bunch of scripts that essentially treat an organization as if it were just a single repo. So apart from Binder's requirements (which seem problematic to me), I don't see a strong argument pushing towards either one repo or many repos.

**Comment by jsignell** [comment]
From looking at https://github.com/dask/dask-examples it seems like the binder files can go into their own dir. But I agree that we shouldn't really be making decisions based on binder.

> What meaningless nesting would there be?

What would the name of the repo be? And would there be any organization in that repo or just dirs each containing one example?

**Comment by jbednar** [comment]
If git submodules worked reasonably one could imagine sharing binder-related code across many repos as a submodule, but they've always been too problematic to be useful.  

The name of the single repo would be  generic, like pyviz-examples, and at the repo level it would have a website explaining how to add new examples, how the infrastructure for building and maintaining them works, etc.  So it wouldn't be meaningless; it would be a meaningful grouping of a bunch of items that we maintain using similar processes and that each have a similar status with respect to each other.  

I wouldn't _expect_ any organization within the repo; seems unlikely that we could come up with any that would be defensible over time.  But perhaps we could consider having some curated sets of environments at the top level that cover a lot of cases, and each project could use one of those if it doesn't have any special requirements otherwise.

**Comment by jbednar** [comment]
Note that none of the above addresses data files, but I would expect that data files of any non-trivial size wouldn't be in the repo, and would be accessed typically via intake in this class of examples.  (In user guides I don't want to assume intake is available and known, but in examples like this it seems like a reasonable approach to expect people to figure out.)

**Comment by jsignell** [comment]
Right I imagine the datafiles would be stored elsewhere and accessed using intake or something similar. I don't really think there would be very much enthusiasm for developing another infrastructure tool, so that probably tips the scales towards one repo.

**Comment by jbednar** [comment]
conda-forge uses multiple repos, of course, but they definitely have developed their own infrastructure tooling to handle that.  For them it's important to be able to set permissions per project, which is presumably why they chose the repo-per-project approach, because external people need to be given maintenance access to just specific projects.  So we should consider that issue here, too -- how likely is it that we need external people maintaining individual topics?  It seems to me that we won't be expecting major continuing updates by external people, unlike c-f, and that those can be done with the usual fork-and-PR model on a single repo, but it's worth mentioning the issue...

**Comment by jlstevens** [comment]
Summarizing my main feelings on this issue after the discussion we had today:

1. Although the ability to tag individual repos is appealing, I think a completely decentralized approach (one repo per topic project) is going to be very hard to maintain.
2. Conversely, an entirely centralized approach with one master repo would also be hard to maintain and would need lots of environment files/anaconda-project files in the same repo.
3. As a result, my conclusion is we should continue with what we have already been doing with EarthML and EarthSim - defining some topic boundaries so that you can have one environment file and have a number of topic notebooks grouped together. Our job then is to decide on some of these topic boundaries...
4. Generally I am very much in favor of defining anaconda projects to make it easy to run and deploy locally or remotely.
5. I think the current approach to pyviz-demos is good and that keeping topics and demos separate (with the ability to cross-link) is appropriate.

**Comment by jbednar** [comment]
@jlstevens: 

1. Agreed
2. The entire idea *is* to have lots of environment files or anaconda-project files per repo, or more precisely, one per directory, i.e. one per topic.  The idea is that people should be able to run an individual example without having to fetch all the dependencies in the world, e.g. using `anaconda-project run`.  That said, for our own purposes as maintainers, we are likely to keep a much smaller number of environments around; I personally would prefer just one.  So we'd need automated tests that the individual environments are sufficient, but I would guess that we typically won't use individual environments in our day to day work.
3. I don't see how topic boundaries are going to be useful here. E.g. how would you propose handling [Datashader's examples](http://datashader.org/topics/index.html)?  They all use datashader, but otherwise don't have any clear topic boundaries, and in general are meant precisely to be a grab bag of topics. Same goes for the examples currently on [panel.pyviz.org](http://panel.pyviz.org), or in the hv showcase. EarthML and EarthSim are special in that they were specifically funded to be a set of topics in that area, but in general our topics are _better_ if they cover as wide a range of domains as possible, whereas forcing things into a domain area encourages the opposite. Plus over time we'll add more areas and want to move items into a newly specific one as it appears, which will break links to that example from everywhere else, and I want to _encourage_ such links, not make them a burden.
4. I too favor anaconda-project, or preferably (if it ever appears) conda-project (as it's more obviously OSS), which can capture the commands needed to run a given example, and has the added benefit of allowing AE5 deployment.
5. As I indicated during the discussion, I fail to see any defensible distinction to make between demos and topics _in terms of how we version them, store them, and maintain them_.  To me, the only difference is that for a demo the user typically starts with the deployed app/dashboard, and only then considers whether to explore the underlying code or to try to adapt it to their own needs.   A topic or example is the opposite, i.e. that it may be deployable, but they start from the docs or the code and see how it all fits together, and only then (and optionally) deploy it.  While that is an important difference for the user, I don't see how it affects how we organize and store things -- in both cases we need to store source code, we need to store some sort of docs, we need an environment specification, we need versioning, etc., etc.  To me all that changes is the typical entry point, which for demos is a running app and for topics/examples is a web page or Jupyter notebook, but because many demos and apps serve dual duty (both showcasing final functionality _and_ showing how to build such a thing yourself), I don't think it's helpful or appropriate to make a distinction between the two at the storage/repo level.  Can't we just solve the storage/repo issue separately from deciding which things to present as demos, which things to present as domain-related topics, and so on?  Those seem quite separable concerns to me.

**Comment by jbednar** [comment]
We should explicitly make a plan for how users will get and work with any of these examples. Right now, datashader users can get all the examples and all the data files by running `datashader examples`, and similarly for `panel`, `holoviews`, etc., in each case pulling the examples out of the Python module source code (for lack of some other better place to store them that's actually reliable).  How should users get them in our new approach?

With the repo-per-project approach, we could imagine tagging all the examples demonstrating `datashader` with a `datashader` tag, and then implementing `datashader examples` to fetch those examples from the repo and set things up ready to run locally.  In that case I'm not sure how we'd handle making sure we had the correct example version to work with our just-installed `datashader`, as both `datashader` and the example are edited over time.  

With the single-repo approach, maybe we could declare such tags some other way, and then fetch the right example directory?

Or maybe `datashader examples` would simply fetch the user manual and other purely Datashader-specific things, with some other way for users to get the other examples?

**Comment by jsignell** [comment]
> Plus over time we'll add more areas and want to move items into a newly specific one as it appears, which will break links to that example from everywhere else, and I want to encourage such links, not make them a burden.

This feels like a big deal to me. I think one of the main things we want to commit to are stable links for these things. 

> Right now, datashader users can get all the examples and all the data files by running datashader examples, and similarly for panel, holoviews, etc., in each case pulling the examples out of the Python module source code (for lack of some other better place to store them that's actually reliable). How should users get them in our new approach?

I don't think this needs to be supported via the CLI. The regular `datashader examples` should contain all the docs that a user needs to get up and running with datashader. If the user then wants to look into a particular topic that should be a separate action (done via git clone or downloading the notebook). I think that action of getting one topic is more comfortable if in the repo-per-project approach (git clone). I worry that otherwise users will be forced to choose between downloading the whole repo of examples or just downloading the notebook, in which case they'll be missing all the good environment, anaconda-project, intake stuff.

On the other hand downloading a whole bunch of topics under the repo-per-project scenario would be really annoying. Unless there were some clever symlinking that we could do to have it both ways.


## Updated Proposal

Having just split intake into intake and intake-examples (new repo), I have a new confidence that we can change our minds later while preserving git history. So I propose making the mega-repo (**One new repo with all the examples in it**) and seeing how it goes. @pyviz/pyviz-dev sound good?

**Comment by jbednar** [comment]
How expensive is it to download all our current examples, minus their data?  Seems like that's not going to be much, compared to a typical dataset size, but maybe I'm being naive.  In any case we could add a command that will fetch a given example from the megarepo as a directory and then run "anaconda-project run" on it (or the equivalent if we find any).

**Comment by jbednar** [comment]
In any case, I think you should go ahead with the mega-repo approach unless @philippjfr or @jlstevens  has a very convincing argument against that and chimes in with it in the next 24h.

**Comment by jsignell** [comment]
> How expensive is it to download all our current examples, minus their data? 

I am not sure because they are scattered across projects, but I agree it wouldn't be too big since we are only checking in empty notebooks.

**Comment by jsignell** [comment]
https://examples.pyviz.org
