### ISSUE TITLE
Unable to install pyviz tutorial

### ISSUE THREAD

**Issue by dovz11** [holoviz/holoviz#175]
Hi,

I'm trying to install the pyviz tutorial as explained on https://pyviz.org/installation.html
My working environment is inside a docker container and the following fails (see below) during the build process or if I run inside the jupyter terminal.
Any ideas or workaround ?

Thanks,
Dov

```
$ sudo conda activate pyviz-tutorial

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
```

**Comment by jbednar** [comment]
Have you tried what it suggests, i.e. running `conda init bash` before `conda activate`?  

BTW, `sudo conda` isn't something I've ever needed myself, and I would hope that most people would never need to do that, though maybe you have some good reason I've never encountered.

**Comment by dovz11** [comment]
Thanks for the reply.  Yes, I tried running `conda init bash` before `conda activate`  and got the response below.  

A key detail to mention here is that I'm running everything inside a docker container on an Ubuntu 16.04 VM on Azure cloud.  There are multiple reasons to run inside a Docker image (simplified setting & deployment flexibility).  I eventually got most of the pyviz tutorial to work after installing the tutorial on a stand alone windows machine and copy the pyviz-example folder manually to an Ubuntu folder mounted by the docker container.  The only things that are still failing on the Tutorial inc everything involve with reading .parq files (like `dd.read_parquet('../data/nyc_taxi_wide.parq').persist()`). I'll open a separate issue for that (see #178)

I'm not sure what would be the correct way to include the pyviz tutorial in a Docker container.  Forwhatever it worth, below are more details of my failed attempt:
The docker image is based on the [all-spark-notebook image](https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook) from the [Jupyter Docker Stacks](https://jupyter-docker-stacks.readthedocs.io/en/latest/index.html).  The Docker file first lines look as below:

```
FROM jupyter/all-spark-notebook:65761486d5d3
USER root
RUN conda update conda
RUN conda update conda
RUN conda init bash
RUN conda create -n pyviz-tutorial python=3.6
RUN conda activate pyviz-tutorial
```
The docker image build output looks as below:
```
Sending build context to Docker daemon  6.144kB
Step 1/36 : FROM jupyter/all-spark-notebook:65761486d5d3
 ---> dd098532dbb2
Step 2/36 : USER root
 ---> Using cache
 ---> f3e1a02c309d
Step 3/36 : RUN conda update conda
 ---> Using cache
 ---> 96ef4dc579f3
Step 4/36 : RUN conda update conda
 ---> Using cache
 ---> cdbb069c88b2
Step 5/36 : RUN conda init bash
 ---> Using cache
 ---> b3f4368310bb
Step 6/36 : RUN conda create -n pyviz-tutorial python=3.6
 ---> Running in 0e6f5957b12a
Collecting package metadata: ...working... done
Solving environment: ...working... done

......
#
# To activate this environment, use:
# > conda activate pyviz-tutorial
#
# To deactivate an active environment, use:
# > conda deactivate
#

Removing intermediate container 0e6f5957b12a
 ---> 7a6c9855ef18
Step 7/36 : RUN conda activate pyviz-tutorial
 ---> Running in f8943301c414

CommandNotFoundError: Your shell has not been properly configured to use 'conda activate'.
To initialize your shell, run

    $ conda init <SHELL_NAME>

Currently supported shells are:
  - bash
  - fish
  - tcsh
  - xonsh
  - zsh
  - powershell

See 'conda init --help' for more information and options.

IMPORTANT: You may need to close and restart your shell after running 'conda init'.
The command '/bin/sh -c conda activate pyviz-tutorial' returned a non-zero code: 1
```

**Comment by jbednar** [comment]
That looks like a conda issue, whether it's a bug or a usage error; nothing to do with pyviz or the pyviz-tutorial per se. (This message happens before it tries to set up the particular environment, so you'd have the same results with any py36 envt).  My guess from the message "You may need to close and restart your shell after running 'conda init'" is that the init procedure isn't fully completed and that you'd need to somehow launch bash again, which of course is tricky if it's part of a Docker script.  

What I've found to work in a somewhat analogous case is to do initialization of the shell the "old way", before conda init was supported, which requires finding some of the setup that conda init does and pasting it into your script directly.  I don't remember where I found the code to do that; it was definitely by snooping around where I wasn't supposed to!  In any case, I'll close this because really your question is about how to activate a conda environment that you just set up, on a shell you just set up, nothing about pyviz, and so I think you'd have to make an issue on https://github.com/conda/conda or see if someone else already has.

**Comment by dovz11** [comment]
Thanks.  You are right.  conda activate doesn't play nicely with docker.  I  found  the following wirteups from people worked around the issues:
[Conda Environments with Docker](https://medium.com/@chadlagore/conda-environments-with-docker-82cdc9d25754)
[Using Docker with Conda Environments](https://fmgdata.kinja.com/using-docker-with-conda-environments-1790901398)

I'll report if I'll get any of this to work..
