### ISSUE TITLE
Dead link to index.html

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#252]
![image](https://user-images.githubusercontent.com/42288570/83384782-44c93a80-a3e8-11ea-9719-a9cfaae18e4b.png)

![image](https://user-images.githubusercontent.com/42288570/83384832-5ad6fb00-a3e8-11ea-9479-3aed01ba9290.png)

#### Solution

Change link from `tutorial/index.html` to `index.ipynb`.

![image](https://user-images.githubusercontent.com/42288570/83384918-85c14f00-a3e8-11ea-8e79-90ece3e428cd.png)

#### Context

As stated in the documentation http://holoviz.org/installation.html

I'm running `jupyter notebook` from the `holoviz-examples` folder.

**Comment by MarcSkovMadsen** [comment]
Ahh. Now I understand the problem. The problem is that you would really like to link to the website. But the links provided will only work from the website. Not from a running notebook.

Don't know how to solve it.

**Comment by MarcSkovMadsen** [comment]
The `installation` link just below has the same problem.

**Comment by jbednar** [comment]
The way we build the website replaces x.ipynb links inside notebooks  with x.html in the rendered HTML pages, so that links to notebooks should work both in notebooks and on the published website.  So here we _could_ change the link to index.ipynb, which should stop the link being broken. 

However, from the context it's actually meant to be pointing to the published version of the website, which means it should point to `http://holoviz.org/tutorial/` whether or not it's on the website or in a live Jupyter notebook. Probably someone mistakenly removed `http://holoviz.org` thinking that it should be a relative link, but here (unlike just about anywhere else in the tutorial) it should link to the rendered, public .html. The same applies to the `installation` link. 

In both cases we do run a link checker on the .html (or at least did at some point!), and these links do work on the HTML version, but we don't have an automated way to check links from within Jupyter.  So please do keep reporting issues like this (or better yet, make a PR to fix them), as we're unlikely ever to click on many of these links when we run Jupyter ourselves. In the meantime, these particular problems should be fixed by #261.
