### ISSUE TITLE
Feedback and suggestions for improvements

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#260]
HoloViz: 0.11.13

#### Context

I am a very experienced user of Panel and a somewhat experienced user of hvplot/ holoviews.

I expect the HoloViz tutorial to be something that

- a new unexperienced user of the HoloViz ecosystem can use to 
   - learn about the ecosystem and how to use it.
   - evaluate whether the ecosystem can be used to solve my use cases

My use cases are end to end from exploration to production. Always with an aim to get to production producing insights, plots and apps for users.

#### Feedback

Overall I can see a lot of effort has gone into showcasing the great power of HoloViz and some of the things that makes the HoloViz ecosystem powerfull.

But unfortunately I think the tutorial could give another impression if you are not experienced in Python and data viz. Or if your focus is to create beautiful, understandable visualizations that can convey your findings and messages.

This feedback is based on the github issues I have created today and the ones I thought about creating but did not have time or energy for.

![image](https://user-images.githubusercontent.com/42288570/83423859-dd34de80-a42b-11ea-887d-5efb4509de50.png)

But somehow these are minor things and can be fixed if some kind of automated testing of the notebooks could be done.

I think the **main problem is actually the "finish" of the examples**. 

And maybe its just me. But if I was to convince a friend, colleague, architect or manager that HoloViz is awesome, then the examples simply have to work + look and feel awesome. It would take some time before they would understand the power of overlaying things, being able to use LaTeX/ KaTeX and being able to work with big data visualizations in the browser via awesome Datashader. 

And they would simply move on instead of spending time on learning why this is awesome.

I think the problem can be summarized in this plot

![image](https://user-images.githubusercontent.com/42288570/83422092-4d8e3080-a429-11ea-96f7-396213588baf.png)

which is used on the tutorial front page and also the end product of `05_Composing_Plots.ipynb`.

So many awesome technologies has been used to create it. The zoom works great.

But It simply does not look awesome. And for me the `.opts(logz=True)` did not work. So it looked like

![image](https://user-images.githubusercontent.com/42288570/83422705-3bf95880-a42a-11ea-9daf-175abdf7f643.png)

And there is a `overflow` on the vertical axis so its a multi step process before I can zoom.

This should be one of the main selling points of holoviz and datashader but I think it works opposite. Simply because of the color selection and the bugs.

Then if I'm still interested in evaluating whether the the HoloViz ecosystem is awesome I might try to explore the gallery. And  I might be able to find an example like https://examples.pyviz.org/nyc_taxi/dashboard.html#nyc-taxi-gallery-dashboard. It looks nice and interactive. I might be able to gain some insights from it. and It might be able to make it look really awesome with some effort. Something I could put to production.

![image](https://user-images.githubusercontent.com/42288570/83423319-16208380-a42b-11ea-9b91-cf46a638e7ea.png)

But it does not work. And I know you have written it at the top and bottom. But who has time to read from top to bottom these days :-) And its grayed out almost like I should not read it.

![image](https://user-images.githubusercontent.com/42288570/83423473-4d8f3000-a42b-11ea-9d77-584110309015.png)

I have experienced this so many times across the HoloViz ecosystem that you don't know if an example should be interactive or not and whether its not working due to that or due to a bug. Its simply a way to loose new users.

Also the introduction `01_Overview.ipynb` you have to be an experienced `data viz` to understand and appreciate. Its very important, but I would save that for later or shorten it a lot. It simply takes a long time to go through and does not convince any one (I believe) that HoloViz is worth spending time on.

I would change this into a 1-4 minutes video show casing the power of HoloViz with great examples that are fast and looks awesome. You have 1-4 minutes to catch peoples attention and tell them why they should bother.

#### Summary

I would say 

- don't publish anything that looks interactive without it being interactive! :-)
- And spend more time on making things look and feel awesome.
- think like you have 10 sec -4 minutes up front to show the new, potential user why HoloViz is worth learning about.

Thanks for all the effort and hard work put into this. 

I'm writing this because I appreciate the hard work and don't want it to be wasted.

**Comment by MarcSkovMadsen** [comment]
But you actually have the chance to use HoloViz and Panel to showcase the power. I believe its not impossible to use Panel to power everything. :-)

Dash for example is too slow to power the Plotly Dash web site and they have stopped using that. My guess is its because potential users would evaluate it as having a slow performance.

Panel/ Bokeh/ Tornado can be fast if used in the right way.

**Comment by earik87** [comment]
I **fully** agree with Marc. 

The potential in Holoviz is 100. But documentations/demos are only using 50 or 60 percent of this potential. 

Today, people do not even read readmes, they try to see if there is a gif or showchase demonstrating what your product does. 

gif or movie > picture > text. 

I suggest that holoviz and its child websites (panel, holoview etc.) needs some tweak in terms of structure / arrangement / esthetics. They do not have to be beautiful, but they can be consistent, and easier to understand what it does and how it does. 

Check this slide here in http://holoviz.org/talks/index.html. In my opinion, this can be in the main page, because it is beautifully explaining what holoviz family does. But it just needs some tweak, the right side of the slide is the message but font size is super small, and probably readers will miss it. 

![image](https://user-images.githubusercontent.com/36437947/89989611-77fa3680-dc81-11ea-9f4b-c87c0f79a829.png)

I realize that on stackoverflow, a lot of holoviz questions are unanswered. This means there are tons of people trying to use it, but support is missing. People do not know that much about it. Not only holoviz members, but we, as a users, should somehow boost the ecosystem. Any ideas?

**Comment by MarcSkovMadsen** [comment]
I see the some of the same problems. HoloViz is starting to a approach a level of maturity where it is really useful and new users are coming in. They need help and guidance. Either in the form of an active community of users or in the form of really useful documentation, examples and starter templates.

I don't know how to solve this as this requires both time and the right skills.

**Comment by jbednar** [comment]
Thanks for the feedback. Indeed, one of the best things that more experienced users can do is to help answer new-user questions on StackOverflow and Discourse. If the answer is obvious to you and not to the newcomer, please let them know what to do, both for them and for all the other folks who stumble upon that post!

And if there are ways we can bring the most compelling and important bits of our docs so that they are front and center, please let us know; it's not always obvious what bits those are (e.g. on my phone I thought you were referring to [this pic](http://holoviz.org/_images/holoviz.mermaid.svg),  not the workflow one above). The more concrete the suggestion (the closer it is to a PR), the more likely we can address it.

I agree with most of the points raised here, and if you want to understand why things are like that, you should know that the core HoloViz devs are all paid to develop features that address specific needs of our clients. The client has a problem, they pay us to develop a solution, and we deliver it! We typically also develop a Jupyter Notebook to demonstrate and document the new feature, and that then becomes part of our docs.  We _also_ answer questions and work on the docs, but those are generally done after hours, whenever we happen to have time and energy left. There is no one paid to promote HoloViz, to support the general public, or to curate the new-user experience. As far as open-source projects go, HoloViz is quite well funded and supported _for_ _functionality_, but there is no corresponding marketing team, UX team, technical writing team, website team, support team, or any other team but the developers.

For the docs in particular, once we've developed an example that demonstrates a new feature, everything else is built automatically from the notebook, which is why you'll see non-interactive plots on the published website, generated from the fully interactive code we wrote. We're fully aware that this is confusing, but it takes a lot of time and effort to develop and maintain a separate web-only version of the documentation, and there just aren't enough hours in the day after we've kept all our clients happy to do extra work like that.

So if anyone has a way to drum up money to pay for a docs overhaul, we'd love to address that! Or if anyone would be willing to work on projects like substituting short videos for the bits where the content should be interactive but isn't, let us know!  In the meantime, we're all trying to juggle all the hats, while focusing first on what we're paid to do and then on whatever else we can fit in.

**Comment by jbednar** [comment]
Closing as now covered by #275.
