### ISSUE TITLE
The procedure entry point could not be located ... error during installation

### ISSUE THREAD

**Issue by MarcSkovMadsen** [holoviz/holoviz#262]
HoloViz: 0.11.3
OS: Windows 10 Enterprise

I'm following the HoloViz installation guide http://holoviz.org/installation.html. When I run `conda install -c pyviz holoviz` I get an error.

```bash
The procedure entry point ?PYWinObject_FromULARGE_INTEGER@@YAPEAI_object@@AEAT_ULARGE_INTEGER@@@Z could not be located in the dynamic link library C:\Users\<USERNAME>\AppData\Local\Continuum\anaconda3\Library\bin\pythoncom37.dll
```

![image](https://user-images.githubusercontent.com/42288570/83480988-f033c700-a49c-11ea-82fb-79f3f9df4fd3.png)

#### Additional Context

I just press "OK" and continue and the tutorial works fine and I don't see any bugs related to this issue.

**Comment by ceball** [comment]
I wonder why it's finding that dll. How is that path related to the environment you're using/where is that path coming from, I wonder?

So, sorry to be pedantic and ask some tiresome questions/steps. I'll be upfront and say, who knows if this will fix it, but it would be useful to know in case it comes up for others. 

Could you confirm that you:
1. are using the latest conda
2. created a new conda environment
3. activated that environment
4. don't have that path in your `PATH` somehow 
5. installed holoviz into that environment

And if you have time:

  6. does it still happen with the newest package? (0.11.6, in case somehow it's related to holoviz dependencies rather than environment)

**Comment by jbednar** [comment]
Closing as we cannot investigate it without the further details requested. Please reopen if you want to provide those details, though do note that we expect the next release to be as a project rather than a conda package like this.
