### ISSUE TITLE
Improvements to the installation instructions

### ISSUE THREAD

**Issue by maximlt** [holoviz/holoviz#317]
The `Installation` page mostly contains instructions to install everything that is required to run the tutorial. I would suggest to move entirely the tutorial instructions to the `Setup` page of the Tutorial.

The main `Installation` page could be in a second step extended with global installation instructions that would be valid for all the HoloViz packages, and would guide users in their install decisions, including for instance:

- when to use conda vs pip?
- when using conda, why choosing pyviz vs. conda-forge vs. defaults?

We could even make it more general, including docs on when and why people should pin their dependencies and how to achieve that (e.g. with anaconda-project for conda)

**Comment by jbednar** [comment]
>I would suggest to move entirely the tutorial instructions to the Setup page of the Tutorial.

Makes sense. The Installation page should mention that the tutorial has its own installation instructions, and that people wanting to run the tutorial should follow those instead so that they can reproduce those results reliably.

I'd be happy to see a draft of the proposed extended instructions with commentary. We could include developer instructions there, or those could go elsewhere.  Not sure if pinning dependencies goes here or not; depends on the flow, I guess!

**Comment by maximlt** [comment]
This was implemented by Demetris, the Installation page has been removed.

![image](https://github.com/holoviz/holoviz/assets/35924738/5704c59d-6204-4c32-80d1-ed21b4c29ff9)
