### ISSUE TITLE
nyc taxi 50k data breaks a lot of tutorial content

### ISSUE THREAD

**Issue by WilyMongooseZero** [holoviz/holoviz#50]
when the city wide data was replaced with the 50k data, there seems to be a lot of content that has been broken, I can get it to run again by replacing the 50k for wide, but its annoying.

**Comment by jbednar** [comment]
Just to clarify, there is no intention for the 50k data to be anything but a poor substitute for the wide dataset. We provide the 50K subset primarily so that our automated testing can verify basic functionality, and additionally as a fallback in case someone cannot download the full dataset, but it's certainly not meant to be what people would use in practice.  Is there some part of our materials that was steering you towards the 50k dataset that we need to fix?

**Comment by jbednar** [comment]
I just checked, and the only place 50k seems to be mentioned is in messages like "If you are low on memory (less than 8 GB) or have not downloaded the full data, you can load only a subset of the data by changing 'nyc_taxi_wide.parq' to 'nyc_taxi_50k.parq'", which is true; it's not for general use.
