### ISSUE TITLE
Make holoviz tutorial available on mybinder

### ISSUE THREAD

**Issue by ceball** [holoviz/holoviz#98]

**Comment by jbednar** [comment]
Just to clarify, in #97 the proposal is to package up all the PyViz tutorials as an envt on mybinder so that people who have any trouble running on their own system can instead work in a mybinder session.  

There's a related proposal where each tutorial page would have a link that would spin up that particular tutorial in a mybinder session, which may or may not be able to use the same setup as the above suggestion.

**Comment by jbednar** [comment]
See examples.dask.org for a starting point.

**Comment by jbednar** [comment]
Done!
